version: 2.1
jobs:
  checkout:
    steps:
      - checkout

  node:
    working_directory: ~/AlanSampleApp/AlanSampleApp
    docker:
      - image: cimg/node:12.16

    steps:
      - run: pwd
      - run: ls -al

      # - restore_cache:
          # key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      # - restore_cache:
          # key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/AlanSampleApp
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
            
  android-build-and-test:
    working_directory: ~/AlanSampleApp/AlanSampleApp/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      # - checkout:
          # path: ~/AlanSampleApp

      - attach_workspace:
          at: ~/AlanSampleApp/AlanSampleApp

      # - restore_cache:
          # key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle


workflows:
  node-android-ios:
    jobs:
      - checkout
      - node:
          requires:
            - checkout
      - android-build-and-test:
          requires:
            - node
            